name: Keep Streamlit Alive

on:
  schedule:
    - cron: "*/15 * * * *" # 15분마다 실행 (슬립 방지 골든타임)
  workflow_dispatch:

jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Streamlit App
        run: |
          # -L: 리다이렉트 추적, -A: 크롬 브라우저 위장
          curl -L --max-time 30 -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" https://8ug2zd7qzwdj5u24nom335.streamlit.app/
